<section class="block_tab">
	<table> 
		<thead>
			<tr>
<?php foreach($tabs as $tab){?>
				<th><?=$tab;?></th>
<?php }?> 
			</tr>
		</thead>
		<tbody>
<?php foreach($type[$me] as $types) : ?>
			<form action="http://corentinp.dijon.codeur.online/Project_J/decoupe/" method="post">
				<tr>
					<td><?=$types[0];?></td>
					<td><?=$types[1];?></td>
					<td><?=$types[2] . " x " . $types[3];?></td>
					<td>
						<select name="epa" multiple>
<?php foreach($types[4] as $types2) : ?>
							<option value="<?=$types2;?>"><?=$types2;?></option>
<?php endforeach; ?>
						</select>
					</td>
					<td>
						<input type="submit" value="Découper "/>
						<input type="hidden" name="ref" value="<?=$types[0];?>" />
						<input type="hidden" name="mat" value="<?=$types[1];?>" />
						<input type="hidden" name="lon1" value="<?=$types[2];?>" />
						<input type="hidden" name="lon2" value="<?=$types[3];?>" />
					</td>
				</tr>
			</form>
<?php
		endforeach;
?>
		</tbody>
	</table>
</section>